---

- name: Diffie-Hellman parameter is generated
  shell: /usr/bin/openssl dhparam -out "{{ _postfix_config.ssl.dhparams.file }}" {{ _postfix_config.ssl.dhparams.size }}
  args:
    chdir:
  when: (encryption != "off") and (_dh_file_st.stat.exists == false)

- name: Diffie-Hellman parameter file has proper permissions
  file:
    path: "{{ _postfix_config.ssl.dhparams.file }} "