---

# TODO custom compilation flags
- name: Postfix is installed via PKG
  pkgng:
    name: postfix 
    state: present

- lineinfile:
    dest: /etc/rc.conf
    regexp: ^{{item}}= 
    line: '{{ item }}="NO"'
  with_items:
    - sendmail
    - sendmail_submit
    - sendmail_outbound
    - sendmail_msp_queue

- command: touch /etc/periodic.conf
  args:
    creates: /etc/periodic.conf

- lineinfile:
    dest: /etc/periodic.conf
    regexp: ^{{item}}=
    line: '{{ item }}="NO"'
  with_items:
    - daily_clean_hoststat_enable
    - daily_status_mail_rejects_enable
    - daily_status_include_submit_mailq
    - daily_submit_queuerun
